spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter
    username: root
    password: 123456
  session:
    timeout: 86400 # session超时时间: 1天
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 全局日期格式
    time-zone: GMT+8 # 时区

  web:
    resources:
      add-mappings: true
      static-locations: file:D:/uploads/

server:
  port: 8080
  servlet:
    context-path: /api
    mulipart:
      max-file-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
